/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/island1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.polySurface43.geometry} material={nodes.polySurface43.material} />
        <mesh geometry={nodes.polySurface44.geometry} material={nodes.polySurface44.material} />
        <mesh geometry={nodes.polySurface80.geometry} material={nodes.polySurface80.material} />
        <mesh geometry={nodes.polySurface81.geometry} material={nodes.polySurface81.material} />
        <mesh geometry={nodes.polySurface82.geometry} material={nodes.polySurface82.material} />
        <mesh geometry={nodes.polySurface83.geometry} material={nodes.polySurface83.material} />
        <mesh geometry={nodes.polySurface43001.geometry} material={nodes.polySurface43001.material} />
        <mesh geometry={nodes.polySurface44001.geometry} material={nodes.polySurface44001.material} />
        <mesh geometry={nodes.polySurface80001.geometry} material={nodes.polySurface80001.material} />
        <mesh geometry={nodes.polySurface81001.geometry} material={nodes.polySurface81001.material} />
        <mesh geometry={nodes.polySurface82001.geometry} material={nodes.polySurface82001.material} />
        <mesh geometry={nodes.polySurface83001.geometry} material={nodes.polySurface83001.material} />
        <mesh geometry={nodes.polySurface43002.geometry} material={nodes.polySurface43002.material} />
        <mesh geometry={nodes.polySurface44002.geometry} material={nodes.polySurface44002.material} />
        <mesh geometry={nodes.polySurface80002.geometry} material={nodes.polySurface80002.material} />
        <mesh geometry={nodes.polySurface81002.geometry} material={nodes.polySurface81002.material} />
        <mesh geometry={nodes.polySurface82002.geometry} material={nodes.polySurface82002.material} />
        <mesh geometry={nodes.polySurface83002.geometry} material={nodes.polySurface83002.material} />
        <mesh geometry={nodes.polySurface84.geometry} material={nodes.polySurface84.material} />
        <mesh geometry={nodes.polySurface85.geometry} material={nodes.polySurface85.material} />
        <mesh geometry={nodes.polySurface86.geometry} material={nodes.polySurface86.material} />
        <mesh geometry={nodes.Cloud007.geometry} material={nodes.Cloud007.material} />
        <mesh geometry={nodes.Cloud008.geometry} material={nodes.Cloud008.material} />
        <mesh geometry={nodes.Cloud009.geometry} material={nodes.Cloud009.material} />
        <mesh geometry={nodes.Cloud010.geometry} material={nodes.Cloud010.material} />
        <mesh geometry={nodes.Cloud011.geometry} material={nodes.Cloud011.material} />
        <mesh geometry={nodes.Cloud012.geometry} material={nodes.Cloud012.material} />
        <mesh geometry={nodes.Cloud013.geometry} material={nodes.Cloud013.material} />
        <mesh geometry={nodes.Cloud2.geometry} material={nodes.Cloud2.material} />
        <mesh geometry={nodes.Cloud3.geometry} material={nodes.Cloud3.material} />
        <mesh geometry={nodes.Mesh006.geometry} material={materials.phong2} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials.phong1} />
        <mesh geometry={nodes.polySurface23.geometry} material={nodes.polySurface23.material} />
        <mesh geometry={nodes.polySurface25.geometry} material={nodes.polySurface25.material} />
        <mesh geometry={nodes.polySurface27.geometry} material={nodes.polySurface27.material} />
        <mesh geometry={nodes.polySurface29.geometry} material={nodes.polySurface29.material} />
        <mesh geometry={nodes.polySurface31.geometry} material={nodes.polySurface31.material} />
        <mesh geometry={nodes.polySurface33.geometry} material={nodes.polySurface33.material} />
        <mesh geometry={nodes.polySurface35.geometry} material={nodes.polySurface35.material} />
        <mesh geometry={nodes.polySurface37.geometry} material={nodes.polySurface37.material} />
        <mesh geometry={nodes.polySurface38.geometry} material={nodes.polySurface38.material} />
        <mesh geometry={nodes.polySurface39.geometry} material={nodes.polySurface39.material} />
        <mesh geometry={nodes.polySurface40.geometry} material={nodes.polySurface40.material} />
        <mesh geometry={nodes.polySurface41.geometry} material={nodes.polySurface41.material} />
        <mesh geometry={nodes.polySurface42.geometry} material={nodes.polySurface42.material} />
        <mesh geometry={nodes.polySurface45.geometry} material={nodes.polySurface45.material} />
        <mesh geometry={nodes.polySurface46.geometry} material={nodes.polySurface46.material} />
        <mesh geometry={nodes.polySurface47.geometry} material={nodes.polySurface47.material} />
        <mesh geometry={nodes.polySurface48.geometry} material={nodes.polySurface48.material} />
        <mesh geometry={nodes.polySurface49.geometry} material={nodes.polySurface49.material} />
        <mesh geometry={nodes.polySurface50.geometry} material={nodes.polySurface50.material} />
        <mesh geometry={nodes.polySurface51.geometry} material={nodes.polySurface51.material} />
        <mesh geometry={nodes.polySurface52.geometry} material={nodes.polySurface52.material} />
        <mesh geometry={nodes.polySurface53.geometry} material={nodes.polySurface53.material} />
        <mesh geometry={nodes.polySurface54.geometry} material={nodes.polySurface54.material} />
        <mesh geometry={nodes.polySurface55.geometry} material={nodes.polySurface55.material} />
        <mesh geometry={nodes.polySurface56.geometry} material={nodes.polySurface56.material} />
        <mesh geometry={nodes.polySurface57.geometry} material={nodes.polySurface57.material} />
        <mesh geometry={nodes.polySurface58.geometry} material={nodes.polySurface58.material} />
        <mesh geometry={nodes.polySurface59.geometry} material={nodes.polySurface59.material} />
        <mesh geometry={nodes.polySurface60.geometry} material={nodes.polySurface60.material} />
        <mesh geometry={nodes.polySurface61.geometry} material={nodes.polySurface61.material} />
        <mesh geometry={nodes.polySurface62.geometry} material={nodes.polySurface62.material} />
        <mesh geometry={nodes.polySurface63.geometry} material={nodes.polySurface63.material} />
        <mesh geometry={nodes.polySurface64.geometry} material={nodes.polySurface64.material} />
        <mesh geometry={nodes.polySurface65.geometry} material={nodes.polySurface65.material} />
        <mesh geometry={nodes.polySurface66.geometry} material={nodes.polySurface66.material} />
        <mesh geometry={nodes.polySurface67.geometry} material={nodes.polySurface67.material} />
        <mesh geometry={nodes.polySurface68.geometry} material={nodes.polySurface68.material} />
        <mesh geometry={nodes.polySurface69.geometry} material={nodes.polySurface69.material} />
        <mesh geometry={nodes.polySurface70.geometry} material={nodes.polySurface70.material} />
        <mesh geometry={nodes.polySurface71.geometry} material={nodes.polySurface71.material} />
        <mesh geometry={nodes.polySurface72.geometry} material={nodes.polySurface72.material} />
        <mesh geometry={nodes.polySurface73.geometry} material={nodes.polySurface73.material} />
        <mesh geometry={nodes.polySurface74.geometry} material={nodes.polySurface74.material} />
        <mesh geometry={nodes.polySurface75.geometry} material={nodes.polySurface75.material} />
        <mesh geometry={nodes.polySurface76.geometry} material={nodes.polySurface76.material} />
        <mesh geometry={nodes.polySurface77.geometry} material={nodes.polySurface77.material} />
        <mesh geometry={nodes.polySurface78.geometry} material={nodes.polySurface78.material} />
        <mesh geometry={nodes.polySurface79.geometry} material={nodes.polySurface79.material} />
        <mesh geometry={nodes.polySurface87.geometry} material={materials.Water} />
      </group>
    </group>
  )
}

useGLTF.preload('/island1.gltf')
